lib/smart_ac_web/router.ex
defmodule SmartAcWeb.Router do
  use SmartAcWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug(Coherence.Authentication.Session)
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug BasicAuth, callback: &SmartAcWeb.Auth.api_authorize/3
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
    # plug SmartAc.ApiAuth
  end

  scope "/", SmartAcWeb do
    pipe_through(:browser)
    get "/", PageController, :index
    resources "/devices", DeviceController, only: [:index, :show]
  end

  scope "/api", SmartAcWeb do
    pipe_through(:api)
  #   # resources "/events", EventsController
    post "/event", API.EventController, :create
    post "/device", API.DeviceController, :create
  end

  scope "/" do
    pipe_through(:browser)
    # resources "/sessions", Coherence.SessionController, only: [:create, :new]
    # resources "/registrations", Coherence.RegistrationController, only: [:new, :create]
    coherence_routes()
  end

  scope "/" do
    pipe_through(:protected)
    # resources "/sessions", Coherence.SessionController, only: [:delete]
    get "/sessions/delete", Coherence.SessionController, :delete
    # resources "/registrations", Coherence.RegistrationController, only: [:show, :edit, :update, :delete]
    # resources "/passwords", Coherence.PasswordController
    # resources "/unlocks", Coherence.UnlockController
    # resources "/invitations", Coherence.InvitationController, only: [:new, :create, :delete]
    coherence_routes(:protected)
    resources "/registrations", SmartAcWeb.Coherence.RegistrationController, only: [:edit, :update]
  end
end

lib/smart_ac_web/views/coherence/layout_view.ex
defmodule SmartAcWeb.Coherence.LayoutView do
  use SmartAcWeb.Coherence, :view
end

lib/smart_ac_web/views/layout_view.ex
defmodule SmartAcWeb.LayoutView do
  use SmartAcWeb, :view
end

lib/smart_ac_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ACME Smart AC</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Quicksand:400,500" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if Coherence.logged_in?(@conn) do %>
          <ul>
            <li><%= link "Log out", to: Routes.session_path(@conn, :delete) %></li>
          </ul>
          <% end %>
        </nav>
        <a href="/" class="logo" >
          <h2>ACME Smart AC</h2>
          <span>Console</span>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <%= if Coherence.logged_in?(@conn) do %>
      <div class="nav-bar">
        <a class="button button-outline" href="/invitations/new">Invite an admin</a>
        <%= link "Manage Users", to: Routes.registration_path(@conn, :show), class: "button" %>
        <a class="button" href="/devices">Devices</a>
      </div>
      <% end %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>